name: obaiah_developers
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  git: ^2.3.2
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#f7f7f7"
  image: assets/images/logo.png
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: MontserratB
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
    - family: ReadexPro
      fonts:
        - asset: assets/fonts/ReadexPro-Regular.ttf
    - family: TajawalReg
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: TajawalB
      fonts:
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
    - family: TajawalL
      fonts:
        - asset: assets/fonts/Tajawal-Light.ttf
